/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MesafeliSatisRouteImport } from './routes/mesafeli-satis'
import { Route as KvkkRouteImport } from './routes/kvkk'
import { Route as IadeRouteImport } from './routes/iade'
import { Route as HelpRouteImport } from './routes/help'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BulkRouteImport } from './routes/bulk'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApiRouteImport } from './routes/api'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicWebhooksIyzicoRouteImport } from './routes/api/public/webhooks/iyzico'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MesafeliSatisRoute = MesafeliSatisRouteImport.update({
  id: '/mesafeli-satis',
  path: '/mesafeli-satis',
  getParentRoute: () => rootRouteImport,
} as any)
const KvkkRoute = KvkkRouteImport.update({
  id: '/kvkk',
  path: '/kvkk',
  getParentRoute: () => rootRouteImport,
} as any)
const IadeRoute = IadeRouteImport.update({
  id: '/iade',
  path: '/iade',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkRoute = BulkRouteImport.update({
  id: '/bulk',
  path: '/bulk',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoute = ApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksIyzicoRoute = ApiPublicWebhooksIyzicoRouteImport.update({
  id: '/public/webhooks/iyzico',
  path: '/public/webhooks/iyzico',
  getParentRoute: () => ApiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/api': typeof ApiRouteWithChildren
  '/auth': typeof AuthRoute
  '/brand': typeof BrandRoute
  '/bulk': typeof BulkRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/iade': typeof IadeRoute
  '/kvkk': typeof KvkkRoute
  '/mesafeli-satis': typeof MesafeliSatisRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/studio': typeof StudioRoute
  '/terms': typeof TermsRoute
  '/api/public/webhooks/iyzico': typeof ApiPublicWebhooksIyzicoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/api': typeof ApiRouteWithChildren
  '/auth': typeof AuthRoute
  '/brand': typeof BrandRoute
  '/bulk': typeof BulkRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/iade': typeof IadeRoute
  '/kvkk': typeof KvkkRoute
  '/mesafeli-satis': typeof MesafeliSatisRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/studio': typeof StudioRoute
  '/terms': typeof TermsRoute
  '/api/public/webhooks/iyzico': typeof ApiPublicWebhooksIyzicoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/api': typeof ApiRouteWithChildren
  '/auth': typeof AuthRoute
  '/brand': typeof BrandRoute
  '/bulk': typeof BulkRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/iade': typeof IadeRoute
  '/kvkk': typeof KvkkRoute
  '/mesafeli-satis': typeof MesafeliSatisRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/studio': typeof StudioRoute
  '/terms': typeof TermsRoute
  '/api/public/webhooks/iyzico': typeof ApiPublicWebhooksIyzicoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/api'
    | '/auth'
    | '/brand'
    | '/bulk'
    | '/contact'
    | '/dashboard'
    | '/help'
    | '/iade'
    | '/kvkk'
    | '/mesafeli-satis'
    | '/pricing'
    | '/privacy'
    | '/studio'
    | '/terms'
    | '/api/public/webhooks/iyzico'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/api'
    | '/auth'
    | '/brand'
    | '/bulk'
    | '/contact'
    | '/dashboard'
    | '/help'
    | '/iade'
    | '/kvkk'
    | '/mesafeli-satis'
    | '/pricing'
    | '/privacy'
    | '/studio'
    | '/terms'
    | '/api/public/webhooks/iyzico'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/api'
    | '/auth'
    | '/brand'
    | '/bulk'
    | '/contact'
    | '/dashboard'
    | '/help'
    | '/iade'
    | '/kvkk'
    | '/mesafeli-satis'
    | '/pricing'
    | '/privacy'
    | '/studio'
    | '/terms'
    | '/api/public/webhooks/iyzico'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ApiRoute: typeof ApiRouteWithChildren
  AuthRoute: typeof AuthRoute
  BrandRoute: typeof BrandRoute
  BulkRoute: typeof BulkRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  HelpRoute: typeof HelpRoute
  IadeRoute: typeof IadeRoute
  KvkkRoute: typeof KvkkRoute
  MesafeliSatisRoute: typeof MesafeliSatisRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  StudioRoute: typeof StudioRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mesafeli-satis': {
      id: '/mesafeli-satis'
      path: '/mesafeli-satis'
      fullPath: '/mesafeli-satis'
      preLoaderRoute: typeof MesafeliSatisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kvkk': {
      id: '/kvkk'
      path: '/kvkk'
      fullPath: '/kvkk'
      preLoaderRoute: typeof KvkkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iade': {
      id: '/iade'
      path: '/iade'
      fullPath: '/iade'
      preLoaderRoute: typeof IadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk': {
      id: '/bulk'
      path: '/bulk'
      fullPath: '/bulk'
      preLoaderRoute: typeof BulkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/iyzico': {
      id: '/api/public/webhooks/iyzico'
      path: '/public/webhooks/iyzico'
      fullPath: '/api/public/webhooks/iyzico'
      preLoaderRoute: typeof ApiPublicWebhooksIyzicoRouteImport
      parentRoute: typeof ApiRoute
    }
  }
}

interface ApiRouteChildren {
  ApiPublicWebhooksIyzicoRoute: typeof ApiPublicWebhooksIyzicoRoute
}

const ApiRouteChildren: ApiRouteChildren = {
  ApiPublicWebhooksIyzicoRoute: ApiPublicWebhooksIyzicoRoute,
}

const ApiRouteWithChildren = ApiRoute._addFileChildren(ApiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ApiRoute: ApiRouteWithChildren,
  AuthRoute: AuthRoute,
  BrandRoute: BrandRoute,
  BulkRoute: BulkRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  HelpRoute: HelpRoute,
  IadeRoute: IadeRoute,
  KvkkRoute: KvkkRoute,
  MesafeliSatisRoute: MesafeliSatisRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  StudioRoute: StudioRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
